### PR TITLE
Update to eslint-config-prettier@2.5.0

### PR DESCRIPTION
**Pull request by lydell**
... which adds exclusions for eslint-plugin-standard.
See https://github.com/prettier/eslint-config-prettier/issues/29

### CODE REVIEW

**Comment by npetruzzelli** [comment]
Hi @lydell ,

Thank you for the contribution and for [`eslint-config-prettier`](https://github.com/prettier/eslint-config-prettier)!

I'm afraid I don't yet have a contributor's agreement set up yet. I wasn't expecting a contribution so soon. I'm going ask for you to update your commit to include a sign off (<https://git-scm.com/docs/git-commit#git-commit--s>).

At first glance, it looks fairly straight forward. One thing I'd ask is that you also update the documentation around line 59 in `README.markdown`. It should look like:

```diff
 {
   "extends": [
     "prettier-standard/lib/base",
     "foo",
     "bar",
-    "prettier"
+    "prettier",
+    "prettier/standard"
   ]
 }
```
At some point I'll need to add an additional paragraph letting the user know why `prettier` and `prettier/standard` must come last, but that is outside the scope of this PR.

I'm mostly certain that this contribution breaks nothing! 2.4 and 2.5 of eslint-config-prettier seem fairly simple and I don't imagine there are breaking changes between eslint 4.0 and 4.6, but I'm still going to review it completely. I'll try to get this done by this weekend as time/work/life allows. If possible, I'll try to work in adding a contributor's doc to the repo by then too.

**Comment by lydell** [comment]
Hi! Thanks for your response.

@pekeler mentioned that he uses this config in prettier/eslint-config-prettier#29. After fixing that issue, I decided to look into this config to see what it does (although I've never used it myself), and decided to make this PR as a heads-up about the new fixes for `standard` in eslint-config-prettier.

I'm closing this now, since I don't use this config myself and don't want to spend more time on it. Feel free to peek at this PR if you feel like taking advantage of the new eslint-config-prettier stuff!

**Comment by npetruzzelli** [comment]
No problem. I know that time is precious all too well! I appreciate the heads up and will make an update of my own based on it as soon as I can. It absolutely matches the spirit of what I created this config for.

@pekeler - It will take me some time to get to this. Not because it's hard, but because I am busy! Until then you should be able to use something like the following:

```json
{
  "extends": [
    "prettier-standard",
    "prettier/standard"
  ]
}
```
Admittedly, it is awkward to look at, but it will effectively be the same as any change I expect to make.

**Comment by npetruzzelli** [comment]
@lydell , @pekeler - I've released an update that addresses this, sorry for the wait!

<https://github.com/npetruzzelli/eslint-config-prettier-standard/releases/tag/v2.0.0>

**Pull request closed without merging**
